name: Update binancep2p every 8 min
on:
  schedule:
    - cron: '*/8 * * * *'   # cada 8 minutos
  workflow_dispatch:        # botón manual
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python update.py
      - name: Commit & push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rates.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update binancep2p" && git push origin main --force)
