name: Update binancep2p every 8 min
on:
  schedule:
    - cron: '*/8 * * * *'   # cada 8 minutos
  workflow_dispatch:        # botón manual
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python update.py
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'chore: update binancep2p'
          push_options: '--force'
